# Generated by Django 3.2.4 on 2021-06-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlh', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField()),
                ('thumbnail', models.URLField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('seller', models.CharField(blank=True, max_length=200, null=True)),
                ('crawl_date', models.DateField()),
                ('crawl_time', models.DateTimeField()),
                ('mrp', models.FloatField()),
                ('available_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('stock', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
